Issue/#9114 scope support
gravitee-io/gravitee-policy-oauth2 pull request #70
Opened 2023-06-29 15:02 UTC by chrysophylax

**Issue**

https://github.com/gravitee-io/issues/issues/9114 

**Description**

Implement fix to handle legacy field name `scp` in claims instead of `scope`.

**Additional context**

2023-06-30 12:22 UTC, gaetanmaisse commented
Thanks for the contribution @chrysophylax!

 For this PR to be reviewed and merged, I would need you to:
 - rebase your PR to get the last version of our CI so it will run for your PR
 - fix any commit issues (we are following conventional commit)
 - fix any build/test/validation issue

or check the `Allow edits from maintainers` and we will do it for you

2023-07-03 14:17 UTC, chrysophylax commented
Fixed comments, all CI pips pass. I assume you can now merge the committed changes to the branch in this project ?

2023-07-04 13:07 UTC, mariano-fernandez requested changes
I think it would be a good idea to add some testing for this

2023-07-04 13:07 UTC, mariano-fernandez commented on src/main/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionResult.java
> +            if (scopesNode.isMissingNode()) scopesNode = oAuth2ResponseJsonNode.path(OAUTH_PAYLOAD_SCOPE_NODE_LEGACY);
```suggestion
            if (scopesNode.isMissingNode()) {
                scopesNode = oAuth2ResponseJsonNode.path(OAUTH_PAYLOAD_SCOPE_NODE_LEGACY);
            }
```

2023-07-04 13:07 UTC, mariano-fernandez commented on src/main/java/io/gravitee/policy/v3/oauth2/Oauth2PolicyV3.java
> +    private static final String OAUTH_PAYLOAD_SCOPE_NODE_LEGACY = "scp";
Can the new constant be `public` as the rest of the constants in the class?

2023-07-04 13:07 UTC, mariano-fernandez commented on src/main/java/io/gravitee/policy/v3/oauth2/Oauth2PolicyV3.java
> +        if (scopesNode.isMissingNode()) scopesNode = oauthResponseNode.path(OAUTH_PAYLOAD_SCOPE_NODE_LEGACY);
```suggestion
        if (scopesNode.isMissingNode()) {
            scopesNode = oauthResponseNode.path(OAUTH_PAYLOAD_SCOPE_NODE_LEGACY);
        }
```

2023-07-05 13:21 UTC, chrysophylax commented
Thanks for the feedback, I have updated per comments.

2023-07-05 13:52 UTC, gaetanmaisse approved these changes

2023-07-05 13:54 UTC, mariano-fernandez approved these changes

2023-07-05 14:02 UTC, merged

2023-07-05 14:05 UTC, graviteeio commented
:tada: This PR is included in version 2.3.1 :tada:

The release is available on:
- `2.3.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-oauth2/releases/tag/2.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: